### ISSUE TITLE
do you have the full code? any new version?

### ISSUE THREAD

**Issue by owenbrno** [clementlefevre/parser3#1]

**Comment by clementlefevre** [comment]
Hi,

This is the full version, you can check this url :
https://simple.wikipedia.org/wiki/Greeting

Regards,

CL.


On Mon, Sep 14, 2015 at 4:50 PM, owenbrno <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clementlefevre/parser3/issues/1>.
>



-- 
CL.
